[tool.poetry]
name = "geo"
version = "0.1.0"
description = ""
authors = ["Vladislav Syrochkin <vlad.dev@heado.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flet = "^0.24.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
